# Generated by Django 2.2.2 on 2019-06-19 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Patient first name', max_length=50)),
                ('last_name', models.CharField(help_text='Patient last name', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('notes', models.CharField(help_text='Notes regarding patient', max_length=500)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this wearable data', primary_key=True, serialize=False)),
                ('filename', models.FileField(upload_to='wearable/')),
                ('time', models.DateTimeField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.PatientData')),
            ],
            options={
                'ordering': ['patient', '-time'],
            },
        ),
        migrations.CreateModel(
            name='WearableAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField()),
                ('annotator', models.CharField(help_text='Annotator of data', max_length=50)),
                ('annotation', models.CharField(blank=True, choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('sfp', 'self pace'), ('slp', 'slow pace'), ('fsp', 'fast pace')], default='prs', help_text='UPDRS Task', max_length=1)),
                ('wearable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.WearableData')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CameraData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this wearable data', primary_key=True, serialize=False)),
                ('filename', models.FileField(upload_to='camera/')),
                ('time', models.DateTimeField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.PatientData')),
            ],
            options={
                'ordering': ['patient', '-time'],
            },
        ),
        migrations.CreateModel(
            name='CameraAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField()),
                ('annotator', models.CharField(help_text='Annotator of data', max_length=50)),
                ('annotation', models.CharField(blank=True, choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('sfp', 'self pace'), ('slp', 'slow pace'), ('fsp', 'fast pace')], default='prs', help_text='UPDRS Task', max_length=1)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sensors.CameraData')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
