# Generated by Django 2.2.2 on 2019-09-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameraannotation",
            name="frame_begin",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cameraannotation",
            name="frame_end",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cameraannotation",
            name="ms_time_begin",
            field=models.CharField(default=1, help_text="hh:mm:ss:msec", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cameraannotation",
            name="ms_time_end",
            field=models.CharField(default=1, help_text="hh:mm:ss:msec", max_length=12),
            preserve_default=False,
        ),
    ]
