# Generated by Django 2.2.2 on 2019-07-29 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraannotation',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='wearableannotation',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='cameraannotation',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.CameraData'),
        ),
        migrations.AlterField(
            model_name='cameradata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.PatientData'),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='wearable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.WearableData'),
        ),
        migrations.AlterField(
            model_name='wearabledata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.PatientData'),
        ),
    ]
