# Generated by Django 2.2.2 on 2019-09-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableDataPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('magnitude', models.PositiveIntegerField()),
                ('frame', models.PositiveIntegerField()),
                ('wearable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_point', to='sensors.WearableData')),
            ],
            options={
                'ordering': ['frame'],
                'permissions': (('can_alter_wearabledata_point', 'Can create or edit wearable data point.'),),
            },
        ),
    ]
