# Generated by Django 2.2.2 on 2019-09-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraannotationcomment',
            options={'ordering': ['annotation', 'timestamp']},
        ),
    ]
