# Generated by Django 2.2.2 on 2019-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotation',
            field=models.CharField(blank=True, choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('sfp', 'self pace'), ('slp', 'slow pace'), ('fsp', 'fast pace')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='annotation',
            field=models.CharField(blank=True, choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('sfp', 'self pace'), ('slp', 'slow pace'), ('fsp', 'fast pace')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
    ]
