# Generated by Django 2.2.2 on 2019-09-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_wearabledatapoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wearableannotation',
            options={'ordering': ['frame'], 'permissions': (('can_alter_wearableannotation', 'Can create or edit wearable annotations.'),)},
        ),
        migrations.RemoveField(
            model_name='wearableannotation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='wearableannotation',
            name='frame',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
