# Generated by Django 2.2.2 on 2019-09-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190918_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_annotations', to='sensors.CameraData'),
        ),
        migrations.AlterField(
            model_name='cameradata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='sensors.PatientData'),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='wearable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_annotations', to='sensors.WearableData'),
        ),
        migrations.AlterField(
            model_name='wearabledata',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wearables', to='sensors.PatientData'),
        ),
    ]
