# Generated by Django 2.2.2 on 2019-07-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20190729_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraannotation',
            name='status',
            field=models.CharField(choices=[('begin', '+'), ('end', '-')], default='begin', max_length=1),
        ),
        migrations.AddField(
            model_name='wearableannotation',
            name='status',
            field=models.CharField(choices=[('begin', '+'), ('end', '-')], default='begin', max_length=1),
        ),
    ]
