# Generated by Django 2.2.2 on 2019-09-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_auto_20190924_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraannotation",
            name="ms_time_begin",
            field=models.CharField(
                help_text="hours:minutes:seconds,mseconds", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="cameraannotation",
            name="ms_time_end",
            field=models.CharField(
                help_text="hours:minutes:seconds,mseconds", max_length=12
            ),
        ),
        migrations.AlterField(
            model_name="patientdata",
            name="date_of_birth",
            field=models.DateField(help_text="Patient date of birth"),
        ),
    ]
