# Generated by Django 2.2.2 on 2019-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190729_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='status',
            field=models.CharField(choices=[('b', '+'), ('e', '-')], default='b', max_length=1),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='status',
            field=models.CharField(choices=[('b', '+'), ('e', '-')], default='b', max_length=1),
        ),
    ]
