# Generated by Django 2.2.2 on 2019-07-22 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190619_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraannotation',
            name='note',
            field=models.CharField(default=django.utils.timezone.now, help_text='Note regarding annotation', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cameradata',
            name='note',
            field=models.CharField(default=django.utils.timezone.now, help_text='Note regarding camera', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wearableannotation',
            name='note',
            field=models.CharField(default=django.utils.timezone.now, help_text='Note regarding annotation', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wearabledata',
            name='note',
            field=models.CharField(default=django.utils.timezone.now, help_text='Note regarding wearable', max_length=500),
            preserve_default=False,
        ),
    ]
