# Generated by Django 2.2.2 on 2019-09-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20190920_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearabledatapoint',
            name='magnitude',
            field=models.FloatField(),
        ),
    ]
