# Generated by Django 2.2.2 on 2019-09-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20190920_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wearableannotation',
            options={'ordering': ['frame_begin'], 'permissions': (('can_alter_wearableannotation', 'Can create or edit wearable annotations.'),)},
        ),
        migrations.RenameField(
            model_name='wearableannotation',
            old_name='frame',
            new_name='frame_begin',
        ),
        migrations.RemoveField(
            model_name='wearableannotation',
            name='status',
        ),
        migrations.AddField(
            model_name='wearableannotation',
            name='frame_end',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
