# Generated by Django 2.2.2 on 2019-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20190920_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradata',
            name='time',
            field=models.DateTimeField(help_text='Session Date & Time'),
        ),
        migrations.AlterField(
            model_name='wearabledata',
            name='time',
            field=models.DateTimeField(help_text='Session Date & Time'),
        ),
    ]
