# Generated by Django 2.2.2 on 2019-07-29 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_auto_20190729_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotation',
            field=models.CharField(choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('nmp', 'normal pace'), ('slp', 'slow pace'), ('fsp', 'fast pace')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
