# Generated by Django 2.2.2 on 2019-08-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_auto_20190729_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraannotation',
            name='frame',
            field=models.CharField(default=250, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wearableannotation',
            name='frame',
            field=models.CharField(default=250, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotation',
            field=models.CharField(choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('nmp', 'normal pace'), ('slp', 'slow pace'), ('fsp', 'fast pace'), ('oth', '(other)')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='annotation',
            field=models.CharField(choices=[('prs', 'prone sup'), ('toe', 'toe tapping'), ('leg', 'leg agility'), ('afc', 'arising from chair'), ('tug', 'timed up and go'), ('nmp', 'normal pace'), ('slp', 'slow pace'), ('fsp', 'fast pace'), ('oth', '(other)')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
    ]
