# Generated by Django 2.2.2 on 2019-08-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_auto_20190809_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraannotation',
            name='frame',
        ),
        migrations.RemoveField(
            model_name='wearableannotation',
            name='frame',
        ),
    ]
