# Generated by Django 2.2.2 on 2019-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20190809_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotation',
            field=models.CharField(choices=[('stp', 'Stoop'), ('asm', 'Asymmetry'), ('ebt', 'En bloc turning'), ('dys', 'Dystonia/Dyskensia'), ('mov', 'Slow movement'), ('oth', 'Other')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='annotation',
            field=models.CharField(choices=[('stp', 'Stoop'), ('asm', 'Asymmetry'), ('ebt', 'En bloc turning'), ('dys', 'Dystonia/Dyskensia'), ('mov', 'Slow movement'), ('oth', 'Other')], default='prs', help_text='UPDRS Task', max_length=3),
        ),
    ]
