# Generated by Django 2.2.2 on 2019-09-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0010_auto_20190903_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotation',
            field=models.CharField(choices=[('stp', 'Stooped Posture'), ('asm', 'Asymmetry'), ('ebt', 'En Bloc Turning'), ('dys', 'Dystonia/Dyskensia'), ('mov', 'Slow Movement'), ('oth', 'Other')], default='oth', help_text='PD Symptom', max_length=3),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='annotation',
            field=models.CharField(choices=[('stp', 'Stooped Posture'), ('asm', 'Asymmetry'), ('ebt', 'En Bloc Turning'), ('dys', 'Dystonia/Dyskensia'), ('mov', 'Slow Movement'), ('oth', 'Other')], default='oth', help_text='PD Symptom', max_length=3),
        ),
    ]
