# Generated by Django 2.2.2 on 2019-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0011_auto_20190904_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='status',
            field=models.CharField(choices=[('b', '+'), ('e', '-')], default='b', help_text='Begin (+) or End (-)', max_length=1),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='status',
            field=models.CharField(choices=[('b', '+'), ('e', '-')], default='b', help_text='Begin (+) or End (-)', max_length=1),
        ),
    ]
