# Generated by Django 2.2.2 on 2019-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0012_auto_20190904_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotation',
            name='annotation',
            field=models.CharField(choices=[('pos', 'Stooped Posture'), ('asm', 'Asymmetry'), ('ebt', 'En Bloc Turning'), ('dys', 'Dystonia/Dyskensia'), ('mov', 'Slow/Hesitant Movement'), ('str', 'Short Stride Length'), ('oth', 'Other')], default='oth', help_text='PD Symptom', max_length=3),
        ),
        migrations.AlterField(
            model_name='wearableannotation',
            name='annotation',
            field=models.CharField(choices=[('pos', 'Stooped Posture'), ('asm', 'Asymmetry'), ('ebt', 'En Bloc Turning'), ('dys', 'Dystonia/Dyskensia'), ('mov', 'Slow/Hesitant Movement'), ('str', 'Short Stride Length'), ('oth', 'Other')], default='oth', help_text='PD Symptom', max_length=3),
        ),
    ]
