# Generated by Django 2.2.2 on 2019-09-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0014_cameraannotationcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotationcomment',
            name='text',
            field=models.CharField(max_length=8000),
        ),
    ]
