# Generated by Django 2.2.2 on 2019-09-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0015_auto_20190916_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraannotationcomment',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.CameraAnnotation'),
        ),
        migrations.AlterField(
            model_name='cameraannotationcomment',
            name='text',
            field=models.TextField(),
        ),
    ]
